--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/supercrafter333/AdminLogin
build-by-default: true
branches:
- master
projects:
  AdminLogin:
    icon: "icon.png"
    path: ""
    libs:
      - src: https://poggit.pmmp.io/ci/CLADevs/FormAPI-4.0/libFormAPI