name: AdminLogin
version: 1.1.1
api: 5.0.0
main: supercrafter333\AdminLogin\AdminLoginLoader
src-namespace-prefix: supercrafter333\AdminLogin
author: supercrafter333
softdepend:
  - "GroupSystem"
  - "RankSystem"